"""Shared configuration constants for the UDP voice MVP."""

SAMPLE_RATE = 48_000
CHANNELS = 1
DTYPE = "int16"
BLOCK_DURATION_MS = 20

DEFAULT_PORT = 5000
RECEIVE_HOST = "0.0.0.0"
SOCKET_TIMEOUT_SECONDS = 1.0
