"""Shared configuration constants for LAN voice app."""

from __future__ import annotations

APP_NAME = "LAN голосовые звонки"
APP_VERSION = "0.2.0"
APP_ORG = "Microlan"
APP_ICON_RELATIVE_PATH = "assets/icon.ico"

SAMPLE_RATE = 48_000
CHANNELS = 1
DTYPE = "int16"
FRAME_DURATION_MS = 20
FRAMES_PER_BUFFER = int(SAMPLE_RATE * FRAME_DURATION_MS / 1000)

DEFAULT_SIGNALING_PORT = 5001
DEFAULT_AUDIO_PORT = 5002
RECEIVE_HOST = "0.0.0.0"

SIGNALING_BUFFER_SIZE = 4096
SIGNALING_POLL_TIMEOUT_SEC = 0.5
CALL_TIMEOUT_SECONDS = 25

AUDIO_QUEUE_MAX_FRAMES = 200
INPUT_LEVEL_EMIT_INTERVAL_SEC = 0.12

MIC_GAIN_MIN = 0.0
MIC_GAIN_MAX = 3.0
MIC_GAIN_DEFAULT = 1.0

NOISE_GATE_THRESHOLD_MIN = 0.0
NOISE_GATE_THRESHOLD_MAX = 0.2
NOISE_GATE_THRESHOLD_DEFAULT = 0.02
NOISE_GATE_ENABLED_DEFAULT = True
NOISE_SUPPRESSION_ENABLED_DEFAULT = False
