"""Shared application constants."""

from __future__ import annotations

SAMPLE_RATE = 48_000
CHANNELS = 1
DTYPE = "int16"
BLOCK_DURATION_MS = 20
BLOCKSIZE = int(SAMPLE_RATE * BLOCK_DURATION_MS / 1000)

DEFAULT_SIGNALING_PORT = 5001
DEFAULT_AUDIO_PORT = 5002
RECEIVE_HOST = "0.0.0.0"

SIGNALING_BUFFER_SIZE = 4096
SIGNALING_POLL_TIMEOUT_SEC = 0.5
AUDIO_QUEUE_MAX_BLOCKS = 200
